export const FETCH_LAUNCH_REQUEST = 'FETCH_LAUNCH_REQUEST';
export const FETCH_LAUNCH_SUCCESS = 'FETCH_LAUNCH_SUCCESS';
export const FETCH_LAUNCH_FAILURE = 'FETCH_LAUNCH_FAILURE';
export const SET_LAUNCH_IND = 'SET_LAUNCH_IND';
export const SET_LANDING_IND = 'SET_LANDING_IND';
export const SET_YEAR = 'SET_YEAR';
